# homeManagerModules.haseen — the per-user half: the Quickshell shell as a
# user service, the theme, and the Hyprland entry file. Pair it with
# nixosModules.haseen (haseen.enable), which provides Hyprland, UWSM and
# greetd.
#
# On the installer path ~/.config/hypr/hyprland.lua is seeded once and then
# belongs to the user (docs/architecture.md §3). Here home-manager owns it
# instead; the user's own settings go in monitors.lua, bindings.lua and
# local.lua next to it, which it includes when present, or in
# haseen.hypr.extraConfig.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.haseen;
  inherit (lib)
    literalExpression
    mkEnableOption
    mkIf
    mkMerge
    mkOption
    types
    ;
  haseenPath = "${cfg.package}/share/haseen";
in
{
  options.haseen = {
    enable = mkEnableOption "the haseen user session (CLI, shell, Hyprland config)";

    package = mkOption {
      type = types.package;
      default = pkgs.callPackage ./package.nix { };
      defaultText = literalExpression "pkgs.callPackage ./nix/package.nix { }";
      description = "The haseen tree (CLI + share/haseen).";
    };

    shell.enable = mkEnableOption "the haseen Quickshell shell as haseen-shell.service" // {
      default = true;
    };

    theme = mkOption {
      type = types.nullOr (types.strMatching "[A-Za-z0-9._-]+");
      default = null;
      example = "tokyo-night";
      description = ''
        Theme applied with `haseen theme set` on every activation. `null`
        leaves the theme to `haseen theme set` at runtime.
      '';
    };

    hypr = {
      enable = mkEnableOption "~/.config/hypr/hyprland.lua loading the haseen Hyprland defaults" // {
        default = true;
      };
      extraConfig = mkOption {
        type = types.lines;
        default = "";
        example = ''hl.config({ general = { gaps_out = 8 } })'';
        description = "Lua appended to hyprland.lua after the haseen defaults.";
      };
    };
  };

  config = mkIf cfg.enable (mkMerge [
    {
      home.packages = [ cfg.package ];
      # Login shells and the systemd user manager (which UWSM launches
      # Hyprland and the shell from) both see the store path.
      home.sessionVariables.HASEEN_PATH = haseenPath;
      systemd.user.sessionVariables.HASEEN_PATH = haseenPath;
    }

    (mkIf cfg.shell.enable {
      systemd.user.services.haseen-shell = {
        Unit = {
          Description = "haseen shell (Quickshell)";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
          Conflicts = [ "dms.service" ];
        };
        Service = {
          ExecStart = "${lib.getExe' cfg.package.quickshell "qs"} -p ${haseenPath}/shell";
          Environment = [ "HASEEN_PATH=${haseenPath}" ];
          Restart = "on-failure";
          RestartSec = 2;
        };
        Install.WantedBy = [ "graphical-session.target" ];
      };
    })

    (mkIf (cfg.theme != null) {
      # Renders into ~/.local/state/haseen; reloading a running session can
      # fail during a boot-time activation, which must not fail the switch.
      home.activation.haseenTheme = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        if ! run ${lib.getExe cfg.package} theme set ${lib.escapeShellArg cfg.theme}; then
            warnEcho "haseen: 'haseen theme set ${cfg.theme}' failed; run it by hand once the session is up"
        fi
      '';
    })

    (mkIf cfg.hypr.enable {
      xdg.configFile."hypr/hyprland.lua".text = ''
        -- Generated by home-manager (haseen.hypr). Edit monitors.lua,
        -- bindings.lua or local.lua next to this file, or haseen.hypr.extraConfig.
        dofile("${haseenPath}/default/hypr/init.lua")
        haseen.include_optional(haseen.paths.state_home .. "/haseen/current/theme/hyprland.lua")
        haseen.include_optional(haseen.paths.config_home .. "/hypr/monitors.lua")
        haseen.include_optional(haseen.paths.config_home .. "/hypr/bindings.lua")
        haseen.include_optional(haseen.paths.config_home .. "/hypr/local.lua")
      ''
      + cfg.hypr.extraConfig;
    })
  ]);
}
