# Adapted from Omarchy config/fcitx5/conf/clipboard.conf (MIT, Copyright (c)
# David Heinemeier Hansson). haseen has its own clipboard panel
# (haseen.clipboard), so fcitx5's clipboard addon keeps no keys of its own.
TriggerKey=
PastePrimaryKey=
