# Adapted from Omarchy config/fcitx5/conf/xcb.conf (MIT, Copyright (c) David
# Heinemeier Hansson). Hyprland owns the XKB layout (and the CapsLock compose
# key, see share/haseen/default/hypr/input.lua); fcitx5 must not push its own
# over XWayland.
Allow Overriding System XKB Settings=False
