package palette

import (
	"fmt"
	"strings"
)

// Result is one wallpaper turned into a haseen theme palette.
type Result struct {
	Seed    string     `json:"seed"`
	Mode    string     `json:"mode"`
	Light   bool       `json:"light"`
	Cached  bool       `json:"cached"`
	Palette [16]string `json:"palette"`
}

// Modes the extractor accepts, in the order `haseen theme wallpaper --help`
// lists them. The full upstream set is wider; these are the ones that make
// sense for a terminal palette.
var Modes = []string{
	"normal", "monochromatic", "analogous", "pastel", "material",
	"colorful", "muted", "bright", "complementary", "triadic",
	"split-complementary", "tetradic", "high-contrast", "duotone",
}

// Generate extracts the 16-colour ANSI palette for one image. The seed is the
// image's content hash: the same picture under another name, or re-saved, is
// not a new seed and costs no work (Result.Cached says which happened).
func Generate(imagePath string, light bool, mode string) (Result, error) {
	if mode == "" {
		mode = "normal"
	}
	if err := validateMode(mode); err != nil {
		return Result{}, err
	}
	seed, err := SeedHash(imagePath)
	if err != nil {
		return Result{}, fmt.Errorf("read %s: %w", imagePath, err)
	}
	result := Result{Seed: seed, Mode: mode, Light: light}

	key := cacheKey(seed, mode, light)
	if cached, ok := loadCached(key); ok {
		result.Palette, result.Cached = cached, true
		return result, nil
	}

	dominant, counts, err := ExtractDominantColors(imagePath, DominantColorsToExtract)
	if err != nil {
		return Result{}, fmt.Errorf("extract colours: %w", err)
	}
	if len(dominant) < 8 {
		return Result{}, fmt.Errorf("not enough colours in %s", imagePath)
	}
	result.Palette = NormalizeBrightness(GeneratePaletteByMode(dominant, normalizeCounts(counts), light, mode))

	if err := saveCached(key, cacheEntry{
		Version: cacheVersion,
		Seed:    seed,
		Mode:    mode,
		Light:   light,
		Palette: result.Palette,
	}); err != nil {
		return result, fmt.Errorf("cache palette: %w", err)
	}
	return result, nil
}

// ColorsTOML renders the palette as haseen's (and Omarchy's) theme format: the
// 16 ANSI slots plus the handful of named keys the templates read. Everything
// else (muted, selection, bright_*, mixes) is derived by
// share/haseen/layers/theme/theme-lib.sh from these, so nothing is written
// twice in two places.
//
// Key choice follows aether internal/template/variables.go: accent defaults to
// blue (color4), the cursor to the foreground, and the selection to a surface
// shade near the background rather than an inverted pair.
// The text is a function of the seed alone — no image path, no timestamp — so
// the same wallpaper under another name produces a byte-identical file and the
// caller can skip the write.
func (r Result) ColorsTOML() string {
	p := r.Palette
	mode := "dark"
	if r.Light {
		mode = "light"
	}
	selection := LightenRGB(p[0], 10)
	if r.Light {
		selection = DarkenRGB(p[0], 85)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `haseen theme wallpaper`: seed %s, %s, %s.\n", r.Seed[:16], r.Mode, mode)
	fmt.Fprintf(&b, "# Regenerated only when the wallpaper's own seed changes.\n")
	fmt.Fprintf(&b, "mode = %q\n\n", mode)
	fmt.Fprintf(&b, "accent = %q\n", p[4])
	fmt.Fprintf(&b, "cursor = %q\n", p[7])
	fmt.Fprintf(&b, "selection = %q\n", selection)
	fmt.Fprintf(&b, "selection_foreground = %q\n", p[0])
	fmt.Fprintf(&b, "selection_background = %q\n\n", selection)
	fmt.Fprintf(&b, "background = %q\n", p[0])
	fmt.Fprintf(&b, "foreground = %q\n\n", p[7])
	for i, c := range p {
		fmt.Fprintf(&b, "color%d = %q\n", i, c)
	}
	return b.String()
}
