-- Generated by scripts/hypr2lua.
-- Source: upstream Greek Noir hyprland.conf (HANCORE-linux/omarchy-greek-noir-theme)
--
-- Modified for haseen (was greek-noir-akane): the active border is a clockwise
-- wipe, a gradient whose faded stop travels round the window (plan 069). The
-- gradient and the seconds per turn are `border_wipe` and `border_wipe_seconds`
-- in the colors.toml beside this file, which haseen-sidecar reads too, so the
-- two ways of turning it cannot disagree:
--   - up to 10 s a turn, Hyprland's own `borderangle` animation turns it, in
--     `loop` style, one turn per `speed` deciseconds. Hyprland refuses a speed
--     above 100, so 10 s is as slow as it goes. borderangle sits under
--     `global` beside `border`, not under it, so looknfeel.lua disabling
--     `border` (the colour fade) leaves it running; "linear" is built in;
--   - slower than that (36 s, the pace the owner runs on luna), borderangle
--     stays off and haseen-sidecar pushes the angle over Hyprland's socket,
--     one degree a frame. It stands aside whenever borderangle loops, so the
--     two never run together.
local MAX_NATIVE_SECONDS = 10

-- colors.toml is flat `key = value` lines; only the two wipe keys are read.
local function wipe_keys()
  local info = type(debug) == "table" and debug.getinfo and debug.getinfo(1, "S")
  local dir = info and type(info.source) == "string" and info.source:match("^@(.*)/[^/]*$")
  if not dir and type(haseen) == "table" and haseen.paths then
    dir = haseen.paths.state_home .. "/haseen/current/theme"
  end
  local keys = {}
  local file = dir and io.open(dir .. "/colors.toml")
  if not file then
    return keys
  end
  for line in file:lines() do
    local key, value = line:match("^%s*([%w_]+)%s*=%s*(.-)%s*$")
    if key == "border_wipe" or key == "border_wipe_seconds" then
      keys[key] = value:match('^"(.*)"$') or value
    end
  end
  file:close()
  return keys
end

local wipe = wipe_keys()
local wipe_colors = {}
for colour in (wipe.border_wipe or ""):gmatch("%S+") do
  table.insert(wipe_colors, colour)
end
if #wipe_colors == 0 then
  -- No colors.toml beside this file: the accent, standing still.
  wipe_colors = { "rgba(F25623ff)" }
end
local wipe_seconds = tonumber(wipe.border_wipe_seconds)

if #wipe_colors > 1 and wipe_seconds and wipe_seconds > 0 and wipe_seconds <= MAX_NATIVE_SECONDS then
  hl.animation({ leaf = "borderangle", enabled = true, speed = wipe_seconds * 10, bezier = "linear", style = "loop" })
else
  hl.animation({ leaf = "borderangle", enabled = false })
end

hl.config({
  general = {
    col = {
      active_border = { colors = wipe_colors, angle = 0 },
      inactive_border = "rgb(171717)",
    },
    border_size = 3,
    gaps_in = 5,
    gaps_out = 5,
  },
  group = {
    col = {
      border_active = { colors = wipe_colors, angle = 0 },
      border_inactive = "rgb(171717)",
    },
    groupbar = {
      col = {
        active = "rgba(706e5e99)",
        inactive = "rgba(17171788)",
      },
      text_color = "rgb(F25623)",
      text_color_inactive = "rgba(88A57Dee)",
    },
  },
  decoration = {
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 8,
      color = "rgba(22,22,22, 0.5)",
    },
  },
})

