<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<!-- haseen font mapping. Generated by `haseen theme set` into
     ~/.local/state/haseen/current/theme/fonts.conf; edits here are overwritten.
     ~/.config/fontconfig/fonts.conf (seeded by `haseen seed user`) includes it,
     and the static script rules in share/haseen/default/fontconfig/arabic.conf
     are included after it.

     The families come from the theme (font_family, font_mono) and from
     ~/.config/haseen/font when `haseen font set` wrote one, so every toolkit
     that asks fontconfig for a generic name follows the same choice as the
     terminals and the shell.

     mode="assign" replaces the whole family list, so every list below has to
     carry its own fallbacks: Arabic (0xProto, Inter and JetBrains have no
     Arabic glyphs) and colour emoji. -->
<fontconfig>
  <match target="pattern">
    <test name="family" qual="any"><string>sans-serif</string></test>
    <edit name="family" mode="assign" binding="strong">
      <string>{{ font_family }}</string>
      <string>Noto Sans</string>
      <string>Noto Sans Arabic</string>
      <string>Noto Naskh Arabic</string>
      <string>Noto Color Emoji</string>
    </edit>
  </match>

  <!-- Serif prefers Naskh: it is the typeset Arabic style, Sans Arabic second. -->
  <match target="pattern">
    <test name="family" qual="any"><string>serif</string></test>
    <edit name="family" mode="assign" binding="strong">
      <string>{{ font_family }}</string>
      <string>Noto Serif</string>
      <string>Noto Naskh Arabic</string>
      <string>Noto Sans Arabic</string>
      <string>Noto Color Emoji</string>
    </edit>
  </match>

  <match target="pattern">
    <test name="family" qual="any"><string>monospace</string></test>
    <edit name="family" mode="assign" binding="strong">
      <string>{{ font_mono }}</string>
      <string>Noto Sans Mono</string>
      <string>Noto Sans Arabic</string>
      <string>Noto Naskh Arabic</string>
      <string>Noto Color Emoji</string>
    </edit>
  </match>

  <!-- Machines migrated from Omarchy still carry /etc/fonts/conf.d/50-omarchy.conf
       (package omarchy-settings, which haseen refuses to install, ADR 0001).
       fontconfig reads /etc/fonts/conf.d before the user config, and that file
       *assigns* the generic names away — sans-serif becomes Liberation Sans,
       serif Liberation Serif, monospace JetBrainsMono Nerd Font — so by the time
       the three rules above run there is no generic name left to match and they
       are dead. Re-mapping what it substituted puts the theme's choice back.
       On a machine that never had Omarchy these rules only fire when an
       application asks for those families by name, which is what it wanted. -->
  <match target="pattern">
    <test name="family" qual="any"><string>Liberation Sans</string></test>
    <edit name="family" mode="assign" binding="strong">
      <string>{{ font_family }}</string>
      <string>Noto Sans</string>
      <string>Noto Sans Arabic</string>
      <string>Noto Naskh Arabic</string>
      <string>Noto Color Emoji</string>
    </edit>
  </match>
  <match target="pattern">
    <test name="family" qual="any"><string>Liberation Serif</string></test>
    <edit name="family" mode="assign" binding="strong">
      <string>{{ font_family }}</string>
      <string>Noto Serif</string>
      <string>Noto Naskh Arabic</string>
      <string>Noto Sans Arabic</string>
      <string>Noto Color Emoji</string>
    </edit>
  </match>
  <!-- Same reason, and it is what `haseen font set` means: an application that
       asks for the font Omarchy pinned gets the one this theme uses. Identity
       while font_mono is JetBrainsMono Nerd Font, which is the default. -->
  <match target="pattern">
    <test name="family" qual="any"><string>JetBrainsMono Nerd Font</string></test>
    <edit name="family" mode="assign" binding="strong">
      <string>{{ font_mono }}</string>
      <string>Noto Sans Mono</string>
      <string>Noto Sans Arabic</string>
      <string>Noto Naskh Arabic</string>
      <string>Noto Color Emoji</string>
    </edit>
  </match>

  <!-- CSS system font stacks. Electron apps, GTK WebKit views and the web apps
       `haseen webapp install` creates ask for these names, not for the generics. -->
  <alias binding="strong">
    <family>system-ui</family>
    <prefer>
      <family>{{ font_family }}</family>
      <family>Noto Sans Arabic</family>
      <family>Noto Naskh Arabic</family>
    </prefer>
  </alias>
  <alias binding="strong">
    <family>-apple-system</family>
    <prefer>
      <family>{{ font_family }}</family>
      <family>Noto Sans Arabic</family>
      <family>Noto Naskh Arabic</family>
    </prefer>
  </alias>
  <alias binding="strong">
    <family>BlinkMacSystemFont</family>
    <prefer>
      <family>{{ font_family }}</family>
      <family>Noto Sans Arabic</family>
      <family>Noto Naskh Arabic</family>
    </prefer>
  </alias>
  <alias>
    <family>ui-monospace</family>
    <default><family>monospace</family></default>
  </alias>
</fontconfig>
