/* haseen theme colours for GTK 3 and GTK 4 (libadwaita named colours).
 * Generated by `haseen theme set`; edits here are overwritten.
 * Use from ~/.config/gtk-4.0/gtk.css (and gtk-3.0/gtk.css):
 *   @import url("file:///home/YOU/.local/state/haseen/current/theme/gtk.css");
 */
@define-color accent_color {{ accent }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};
@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};
@define-color view_bg_color {{ background }};
@define-color view_fg_color {{ foreground }};
@define-color headerbar_bg_color {{ mix background foreground 6% }};
@define-color headerbar_fg_color {{ foreground }};
@define-color sidebar_bg_color {{ mix background foreground 6% }};
@define-color sidebar_fg_color {{ foreground }};
@define-color card_bg_color {{ mix background foreground 6% }};
@define-color card_fg_color {{ foreground }};
@define-color popover_bg_color {{ mix background foreground 12% }};
@define-color popover_fg_color {{ foreground }};
@define-color dialog_bg_color {{ mix background foreground 6% }};
@define-color dialog_fg_color {{ foreground }};
@define-color destructive_color {{ red }};
@define-color error_color {{ red }};
@define-color warning_color {{ yellow }};
@define-color success_color {{ green }};
@define-color borders {{ mix background foreground 20% }};
