/* haseen theme colours for GTK 3 and GTK 4 (libadwaita named colours).
 * Generated by `haseen theme set`; edits here are overwritten.
 * `haseen theme set` seeds ~/.config/gtk-4.0/gtk.css and gtk-3.0/gtk.css
 * once with an @import of this file. GTK loads those at user priority, above
 * libadwaita's palette and an app's own stylesheet, and libadwaita 1.6+ binds
 * its --window-bg-color style variables to these names, so the colours below
 * reach every widget.
 */
@define-color accent_color {{ accent }};
@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};
@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};
@define-color view_bg_color {{ background }};
@define-color view_fg_color {{ foreground }};
@define-color headerbar_bg_color {{ mix background foreground 6% }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_border_color {{ foreground }};
@define-color headerbar_backdrop_color {{ background }};
@define-color sidebar_bg_color {{ mix background foreground 6% }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ mix background foreground 4% }};
@define-color secondary_sidebar_bg_color {{ mix background foreground 4% }};
@define-color secondary_sidebar_fg_color {{ foreground }};
@define-color secondary_sidebar_backdrop_color {{ mix background foreground 3% }};
@define-color card_bg_color {{ mix background foreground 6% }};
@define-color card_fg_color {{ foreground }};
@define-color popover_bg_color {{ mix background foreground 12% }};
@define-color popover_fg_color {{ foreground }};
@define-color dialog_bg_color {{ mix background foreground 6% }};
@define-color dialog_fg_color {{ foreground }};
@define-color thumbnail_bg_color {{ mix background foreground 12% }};
@define-color thumbnail_fg_color {{ foreground }};
@define-color destructive_color {{ red }};
@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};
@define-color error_color {{ red }};
@define-color error_bg_color {{ red }};
@define-color error_fg_color {{ background }};
@define-color warning_color {{ yellow }};
@define-color warning_bg_color {{ yellow }};
@define-color warning_fg_color {{ background }};
@define-color success_color {{ green }};
@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};
@define-color borders {{ mix background foreground 20% }};
/* GTK 3 names (libadwaita aliases them to the ones above). */
@define-color theme_bg_color {{ background }};
@define-color theme_fg_color {{ foreground }};
@define-color theme_base_color {{ background }};
@define-color theme_text_color {{ foreground }};
@define-color theme_selected_bg_color {{ accent }};
@define-color theme_selected_fg_color {{ background }};
