/* haseen theme colours for satty (the screenshot annotator).
 * Generated by `haseen theme set`; edits here are overwritten.
 * ~/.config/satty/overrides.css is a symlink to this render
 * (share/haseen/seeds/80-capture.sh). Satty 0.22.0 reads the file as plain
 * CSS and falls back to its built-in stylesheet when it is missing, so a
 * dangling link before the first theme is applied is harmless.
 *
 * Only the chrome is themed. The annotation palette in satty's config.toml
 * stays static high-contrast on purpose: annotations are drawn on a picture
 * of the themed screen, so theme-derived arrow colours would be the one thing
 * on the shot you cannot see.
 *
 * Classes from Satty 0.22.0 src/assets/default.css. */
.outer_box {
  background-color: {{ mix background foreground 6% }};
}

.inner_box {
  background-color: {{ background }};
}

.toolbar {
  color: {{ foreground }};
  background-color: {{ mix background foreground 6% }};
}

.toast {
  color: {{ foreground }};
  background-color: {{ mix background foreground 12% }};
  border-radius: {{ radius }}px;
}

button.editing {
  color: {{ accent }};
}
