-- Generated by scripts/hypr2lua.
-- Source: upstream Greek Noir hyprland.conf (HANCORE-linux/omarchy-greek-noir-theme)
--
-- Modified for greek-noir-akane: the active border is a clockwise wipe.
-- The gradient's `angle` is fixed in the config, so the rotation is delegated
-- to Hyprland's own `borderangle` animation rather than a per-frame loop.
-- (hl.config is load-time only - re-calling it from hl.timer does not apply,
-- and hl.dsp.cmd is a deleted shim that silently no-ops; see
-- .config/hypr/scripts/bit.sh.)
local wipe_colors = { "rgba(F25623ff)", "rgba(F25623cc)", "rgba(F2562311)", "rgba(F25623cc)" }

hl.config({
  general = {
    col = {
      active_border = { colors = wipe_colors, angle = 0 },
      inactive_border = "rgb(171717)",
    },
    border_size = 3,
    gaps_in = 5,
    gaps_out = 5,
  },
  group = {
    col = {
      border_active = { colors = wipe_colors, angle = 0 },
      border_inactive = "rgb(171717)",
    },
    groupbar = {
      col = {
        active = "rgba(706e5e99)",
        inactive = "rgba(17171788)",
      },
      text_color = "rgb(F25623)",
      text_color_inactive = "rgba(88A57Dee)",
    },
  },
  decoration = {
    rounding = 4,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 8,
      range = 8,
      color = "rgba(22,22,22, 0.5)",
    },
  },
})

